"""
Unit tests for P10 programmatic detectors:
- THROAT_CLEARING
- PROMOTIONAL_LANGUAGE
- INFLATED_SYMBOLISM
- PASSIVE_VOICE_OVERUSE
- PARALLEL_STRUCTURE
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import json
from tools.deai_engine import _detect_programmatic_signals


def _signal_types(text: str) -> set:
    """Helper: return set of signal_type names detected."""
    return {s.signal_type for s in _detect_programmatic_signals(text)}


# ─── THROAT_CLEARING ──────────────────────────────────────────────────────────

def test_throat_clearing_fires_on_two_phrases():
    text = (
        "It is important to note that the model converges slowly. "
        "The learning rate was set to 0.001. "
        "It bears mentioning that the batch size affects stability. "
        "We trained for 100 epochs with early stopping."
    )
    assert "THROAT_CLEARING" in _signal_types(text)


def test_throat_clearing_silent_on_single_phrase():
    text = (
        "It is worth noting that the results are preliminary. "
        "The main finding is a 15% improvement in F1 score. "
        "We validated on three separate test sets."
    )
    assert "THROAT_CLEARING" not in _signal_types(text)


def test_throat_clearing_fires_on_gold_012():
    case = json.loads(Path("eval/gold_deai/deai_gold_012.json").read_text())
    assert "THROAT_CLEARING" in _signal_types(case["ai_text"])


# ─── PROMOTIONAL_LANGUAGE ─────────────────────────────────────────────────────

def test_promotional_fires_on_multiple_terms():
    text = (
        "This groundbreaking approach revolutionizes the field of NLP. "
        "Our unprecedented results demonstrate cutting-edge performance. "
        "The model achieves remarkable success on all benchmarks."
    )
    assert "PROMOTIONAL_LANGUAGE" in _signal_types(text)


def test_promotional_silent_on_normal_academic():
    text = (
        "Our approach improves upon the baseline by 3.2 points. "
        "The results suggest moderate gains in efficiency. "
        "Further work is needed to validate these findings."
    )
    assert "PROMOTIONAL_LANGUAGE" not in _signal_types(text)


def test_promotional_fires_on_gold_011():
    case = json.loads(Path("eval/gold_deai/deai_gold_011.json").read_text())
    assert "PROMOTIONAL_LANGUAGE" in _signal_types(case["ai_text"])


# ─── INFLATED_SYMBOLISM ──────────────────────────────────────────────────────

def test_symbolism_fires_on_tapestry_testament():
    text = (
        "The digital humanities represent a rich tapestry of inquiry. "
        "This convergence stands as a testament to scholarly progress. "
        "Computational methods form the bedrock of modern analysis."
    )
    assert "INFLATED_SYMBOLISM" in _signal_types(text)


def test_symbolism_silent_on_concrete_language():
    text = (
        "We analyze three datasets using logistic regression. "
        "The coefficient estimates are presented in Table 2. "
        "Standard errors are clustered at the firm level."
    )
    assert "INFLATED_SYMBOLISM" not in _signal_types(text)


def test_symbolism_fires_on_gold_014():
    case = json.loads(Path("eval/gold_deai/deai_gold_014.json").read_text())
    assert "INFLATED_SYMBOLISM" in _signal_types(case["ai_text"])


# ─── PASSIVE_VOICE_OVERUSE ────────────────────────────────────────────────────

def test_passive_fires_on_excessive_passive():
    text = (
        "It has been recognized that RAG is critical. "
        "A dense retriever is employed to fetch passages. "
        "The response is generated by the language model. "
        "Documents are concatenated with the query. "
        "It has been observed that quality improves. "
        "It has been demonstrated that this works well."
    )
    assert "PASSIVE_VOICE_OVERUSE" in _signal_types(text)


def test_passive_silent_on_methods_section():
    text = (
        "Participants were recruited from a university population. "
        "Written informed consent was obtained from all subjects. "
        "The study protocol was approved by the IRB. "
        "Participants were randomly assigned to conditions. "
        "Data were collected over a 6-week period. "
        "Samples were analyzed using mass spectrometry."
    )
    # Methods-section verbs should suppress the detector
    assert "PASSIVE_VOICE_OVERUSE" not in _signal_types(text)


def test_passive_fires_on_gold_007():
    case = json.loads(Path("eval/gold_deai/deai_gold_007.json").read_text())
    assert "PASSIVE_VOICE_OVERUSE" in _signal_types(case["ai_text"])


def test_passive_silent_on_gold_017_negative():
    case = json.loads(Path("eval/gold_deai/deai_gold_017.json").read_text())
    assert "PASSIVE_VOICE_OVERUSE" not in _signal_types(case["ai_text"])


# ─── PARALLEL_STRUCTURE ───────────────────────────────────────────────────────

def test_parallel_fires_on_triple_constructions():
    text = (
        "The system aims to modify sequences with precision, "
        "to target specific loci with accuracy, and to achieve outcomes in disorders. "
        "It operates by recognizing sequences, by cleaving DNA at sites, "
        "and by facilitating repair through templates. "
        "Research focuses on improving efficiency, on reducing off-targets, "
        "and on expanding the range of editable sites. "
        "Teams work by identifying mutations, by designing guides, "
        "and by validating corrections in model organisms."
    )
    assert "PARALLEL_STRUCTURE" in _signal_types(text)


def test_parallel_silent_on_varied_structure():
    text = (
        "We first analyze the data using regression. "
        "The results show a clear trend toward improvement. "
        "However, the effect size remains modest at best. "
        "Further work should examine boundary conditions."
    )
    assert "PARALLEL_STRUCTURE" not in _signal_types(text)


def test_parallel_fires_on_gold_016():
    case = json.loads(Path("eval/gold_deai/deai_gold_016.json").read_text())
    assert "PARALLEL_STRUCTURE" in _signal_types(case["ai_text"])


# ─── Cross-cutting: no false positives on clean text ──────────────────────────

def test_clean_academic_text_minimal_signals():
    """A well-written academic paragraph should trigger very few signals."""
    text = (
        "We examine the effect of minimum wage increases on employment "
        "in the restaurant industry. Using a difference-in-differences design "
        "that exploits state-level policy variation, we find that a 10% increase "
        "in the minimum wage reduces employment by 1.2 percentage points. "
        "This estimate is robust to alternative specifications and sample restrictions. "
        "Our findings contribute to the ongoing debate about the employment effects "
        "of minimum wage legislation."
    )
    signals = _signal_types(text)
    # Should NOT trigger any of the P10 signals
    p10_signals = {
        "THROAT_CLEARING", "PROMOTIONAL_LANGUAGE", "INFLATED_SYMBOLISM",
        "PASSIVE_VOICE_OVERUSE", "PARALLEL_STRUCTURE",
    }
    false_positives = signals & p10_signals
    assert len(false_positives) == 0, f"False positives: {false_positives}"


if __name__ == "__main__":
    import pytest
    pytest.main([__file__, "-v"])
